version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/waiterapp
      - PORT=3001
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
