services:
  - type: web
    name: waiter-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://...
      - key: RABBITMQ_URL
        value: amqp://admin:admin@...
      - key: PORT
        value: 3000

  - type: worker
    name: waiter-worker-order
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: node dist/workers/orderWorker.js
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://...
      - key: RABBITMQ_URL
        value: amqp://admin:admin@...

  - type: worker
    name: waiter-worker-status
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: node dist/workers/statusWorker.js
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://...
      - key: RABBITMQ_URL
        value: amqp://admin:admin@...
